#!/bin/bash
cd /usr/local/xcap/drivers
sudo rmmod pixci
sudo rm /lib/modules/5.4.0-58-generic/kernel/drivers/misc/pixci.ko
sudo ./pixci.sh install /usr/local/xcap/drivers /usr/local/xcap/drivers/x86_64/5.4.0-58-generic
