#!/bin/bash

if (( $EUID != 0 )); then
    echo "Please run as root"
    exit
fi

printf "Installing dependencies."
apt-get install cmake unzip gcc g++ python2  python2-dev python-numpy python3-dev python3-numpy python3-pip libavcodec-dev libavformat-dev libswscale-dev libgstreamer-plugins-base1.0-dev libgstreamer1.0-dev -y 2> installation.log
printf "."
apt-get install libgtk2.0-dev libgtk-3-dev libpng-dev  libjpeg-dev libopenexr-dev libtiff-dev libwebp-dev libavresample-dev default-jdk openjdk-8-jdk libgtk2.0-dev pkg-config libavcodec-dev libavformat-dev libswscale-dev -y 2>> installation.log
printf "."
apt-get install libtbb2 libtbb-dev libjpeg-dev libpng-dev libtiff-dev libdc1394-22-dev liblcms2-dev  libtiff-dev libpng-dev libz-dev libatlas-base-dev libatlas3-base liblapacke-dev libopenblas-dev -y 2>> installation.log
printf "."
apt-get install libjsoncpp-dev libc6:i386 libgcc1:i386 gcc-4.6-base:i386 libstdc++5:i386 libstdc++6:i386 git -y 2>> installation.log
printf "."
pip3 install pybind11 2>> installation.log
echo "done"

