#!/bin/bash

if (( $EUID != 0 )); then
    echo "Please run as root"
    exit
fi

SETUP_PATH=$(pwd)

tmp_dir=$(mktemp -d -t ci-XXXXXXXXXX)

cd $tmp_dir

#cloning opencv
echo "Cloning opencv..."
git clone https://github.com/opencv/opencv.git
echo "Cloning opencv_contrib..."
git clone https://github.com/opencv/opencv_contrib.git

echo "Preparing opencv..."
cd opencv
mkdir build
cd build
cmake -D CMAKE_BUILD_TYPE=RELEASE -D WITH_TBB=ON -D WITH_OPENMP=ON -D WITH_IPP=ON -D BUILD_EXAMPLES=OFF -D WITH_NVCUVID=ON -D WITH_CUDA=ON -D BUILD_DOCS=OFF -D BUILD_PERF_TESTS=OFF -D BUILD_TESTS=OFF -D WITH_CSTRIPES=ON -D WITH_OPENCL=ON -D CMAKE_INSTALL_PREFIX=/usr/local -D OPENCV_EXTRA_MODULES_PATH=../../opencv_contrib/modules -D OPENCV_ENABLE_NONFREE=ON .. 2>> installation.log
echo "Compiling opencv..."
make -j 20

echo "Installing opencv..."
make install
